version: '3'
services:
  et:
    build:
      context: ../../
      dockerfile: docker/test_server/Dockerfile

    ports:
      - '${PORT}:${PORT}'
    volumes:
      - rvm:/usr/local/rvm
      - global_node_modules:/usr/lib/node_modules
      - ../../systems:/home/app/systems
      - ./public:/home/app/public
      - et1_node_modules:/home/app/systems/et1/node_modules
      - et3_node_modules:/home/app/systems/et3/node_modules
      - api_node_modules:/home/app/systems/api/node_modules
      - admin_node_modules:/home/app/systems/admin/node_modules
      - ./config.json:/home/app/js/S3/config.json
      - ./webapp.conf:/etc/nginx/sites-available/webapp.conf.template
    environment:
      DB_HOST: 'db'
      DB_USERNAME: 'postgres'
      SECRET_KEY_BASE: sdlkjewfkjhfviuhduihenrjk435r89esfd7cv983qh2n4r3q27yh4u5rtfg
      REDIS_HOST: redis
      AWS_ACCESS_KEY_ID: accessKey1
      AWS_SECRET_ACCESS_KEY: verySecretKey1
      AWS_REGION: 'us-east-1'
      AWS_ENDPOINT: 'http://s3.docker.test:8000'
      AWS_S3_FORCE_PATH_STYLE: 'true'
      S3_UPLOAD_BUCKET: 'etapibucket'
      RAILS_ENV: 'production' # Caution - ET1 runs as local
      PORT: ${PORT}
    command: /bin/bash -c "envsubst '$$PORT' < /etc/nginx/sites-available/webapp.conf.template > /etc/nginx/sites-enabled/webapp.conf && /sbin/my_init"
    networks:
      et_full_system:
        aliases:
          - etapi.et
          - admin.et
          - et1.et
          - et3.et
          - s3.et

#command: bash -lc "cd /home/app/systems/api && REDIS_DATABASE=2 bundle exec sidekiq"
  db:
    image: postgres:9.3.5
    networks:
      - et_full_system
    ports:
      - "${DB_PORT:-0}:5432"
  redis:
    image: redis
    ports:
      - "${REDIS_PORT:-0}:6379"
    networks:
      - et_full_system
  smtp:
    image: mailhog/mailhog:latest
    ports:
      - "${MAILHOG_PORT:-0}:8025"
    logging:
        driver: 'none'  # disable saving logs
    networks:
      - et_full_system

volumes:
  rvm:
  global_node_modules:
  et1_node_modules:
  et3_node_modules:
  s3_node_modules:
  api_node_modules:
  admin_node_modules:
networks:
  et_full_system:


