version: '3'
services:
  et:
    build:
      context: ../../
      dockerfile: docker/test_server/Dockerfile

    ports:
      - '3100:80'
    volumes:
      - rvm:/usr/local/rvm
    environment:
      DB_HOST: 'db'
      DB_USERNAME: 'postgres'
  db:
    image: postgres:9.3.5
volumes:
  rvm:


