version: '3'
services:
  et1:
    build:
      context: ../../systems/et1
    links:
      - et1_db
      - et1_redis
      - smtp
      - et_api
      - et_admin
    ports:
      - 8080:8080
    environment:
      RAILS_ENV: local
      DB_HOST: et1_db
      DB_USERNAME: postgres
      DB_NAME: et1db
      WEB_CONCURRENCY: 2
      ASSET_HOST: anything
      HTTP_OPEN_TIMEOUT_S: 1
      HTTP_READ_TIMEOUT_S: 1
      REDIS_URL: redis://et1_redis:6379
      SECRET_KEY_BASE: dsjeflsdshewje23q896edc7dsufhsekjh4321ueirdasy6890
      SMTP_HOSTNAME: smtp
      SMTP_PORT: 1025
      JADU_API: http://et_api:8080/api/v1/
      AWS_ACCESS_KEY_ID:
      AWS_SECRET_ACCESS_KEY:
      S3_UPLOAD_BUCKET:
    env_file: ./.env

    volumes:
      - ./Procfile:/usr/src/app/Procfile
    command: bash -c "gem install foreman; bundle; bundle exec rake db:create; bundle exec rake db:migrate; bundle exec rake assets:precompile; foreman start"
    networks:
      - et_full_system
  et1_redis:
    image: redis
    ports:
      - 6379
    networks:
      - et_full_system

  et1_db:
    image: postgres:9.3.5
    networks:
      - et_full_system
  smtp:
    image: mailhog/mailhog:latest
    networks:
      - et_full_system
  et_api:
    build:
      context: ../../systems/api
    environment:
      WEB_CONCURRENCY: 2
      SECRET_KEY_BASE: sdlkjewfkjhfviuhduihenrjk435r89esfd7cv983qh2n4r3q27yh4u5rtfg
    networks:
      - et_full_system
    volumes:
      - ../../systems/api/log:/usr/src/app/log
  et_admin:
    build:
      context: ../../systems/admin
    environment:
      WEB_CONCURRENCY: 2
      SECRET_KEY_BASE: sdlkjewfkjhfviuhduihenrjk435r89esfd7cv983qh2n4r3q27yh4u5rtfg
      DEVISE_SECRET_KEY: JK3N45KH56743JN25J1B5H43B24H35BJ6575KN21NRNKFASDF89DU23I4NK5TGKFD
    networks:
      - et_full_system
    volumes:
      - ../../systems/admin/log:/usr/src/app/log
    ports:
      - 8081:8080
networks:
  et_full_system: